---
demo-int
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: acm-poc-users
users:
  - poc-user
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: acm-poc
  namespace: openshift-gitops
spec:
  description: ACM PoC
  sourceRepos:
    - '*'
  destinations:
    - namespace: demo-app-*
      server: '*'
  roles:
    - name: syncer
      description: Puede ver y sincronizar apps del proyecto
      policies:
        - p, proj:acm-poc:syncer, applications, get, acm-poc/*, allow
        - p, proj:acm-poc:syncer, applications, sync, acm-poc/*, allow
      groups:
        - acm-poc-users
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: workloads-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - workloads
# oc create clusterrolebinding poc-acm-view --clusterrole=view --group=acm-poc-users
# argocd -> spec.resourceTrackingMethod: annotation+label
---
