apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          # Lista de clusters obtenida por ACM
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: workloads-placement
              requeueAfterSeconds: 180
          # Lista de entornos
          - list:
              elements:
                - env: int 
                  namespace: demo-app-int
                - env: pre 
                  namespace: demo-app-pre
  template:
    metadata:
      # appName-clusterName-env
      name: demo-app-{{ .name }}-{{ .env }}
    spec:
      project: acm-poc
      sources:
        - repoURL: 'https://github.com/clbartolome/acm-tools'
          targetRevision: 'master'
          path: demo-app-gitops/environments/{{ .env }}
      destination:
        server: '{{ .server }}'
        namespace: '{{ .namespace }}'